### ISSUE TITLE
Ceremonias

### ISSUE THREAD

**Issue by Gonzaloemm81** [Gonzaloemm81/Grupo-ISPC#1]
Extraer del material sobre Scrum el concepto y los tipos de Ceremonias.

**Comment by EmiNorte** [comment]
RESUMEN DE CONCEPTOS https://www.youtube.com/watch?v=Ziuz1WqFqLA

**Comment by EmiNorte** [comment]
SPRINT: PIQUE, ESPRINTAR, CORRER A TODA VELOCIDAD
SPRINT: run at full speed over a short distance.
