### ISSUE TITLE
Resumen Bases de datos.

### ISSUE THREAD

**Issue by Gonzaloemm81** [Gonzaloemm81/Grupo-ISPC#4]
Agregar al archivo de **Base de Datos** conceptos generales. Contenido previo a la recopilación  de conocimientos(examen).
Contenido en la [_`Guía de estudio Introducción a las Base de `Datos`_](_https://acceso.ispc.edu.ar/mod/book/view.php?id=13937_)`

**Comment by natiargch** [comment]
Intro
El término bases de datos fue escuchado por primera vez en un simposio celebrado
 en California en 1963.se puede decir que una base de datos es un conjunto de 
información  relacionada que se encuentra agrupada o estructurada.
Desde el punto de vista informático, una base de datos es un sistema formado por
 un conjunto de datos almacenados en discos que permiten el acceso directo a ellos
 y un conjunto de programas que manipulen ese conjunto de datos.Por su parte, 
un sistema de Gestión de Bases de datos es un tipo de software muy especifico
 dedicado a servir de interfaz entre la base de datos, el usuario y las aplicaciones
 que la utilizan.  una agrupación de programas que sirven para definir, construir y
 manipular una base de datos, permitiendo así almacenar y posteriormente acceder a los
 datos de forma rápida y estructurada.

**Comment by natiargch** [comment]
Orígenes
Los orígenes de las bases de datos se remontan a la Antigüedad donde ya existían
 bibliotecas y toda clase de registros. también se utilizaban para recoger información 
sobre las cosechas y censos.
El uso de las bases de datos se desarrolló a partir de las necesidades de almacenar 
grandes cantidades de información o datos.desde la aparición de las primeras computadoras, 
el concepto de bases de datos ha estado siempre ligado a la informática.
En 1884 Herman Hollerith creó la máquina automática de tarjetas perforadas, 
siendo nombrado así el primer ingeniero estadístico de la historia
en los 50's se da origen a las cintas magnéticas, para automatizar
 la información y hacer respaldos.con la desventaja de que solo se podía hacer de forma
 secuencial.Cada programa trataba como máximo un fichero maestro.
A medida que se fueron introduciendo las líneas de comunicación, los terminales y los 
discos, se fueron escribiendo programas que permitían a varios usuarios consultar los 
mismos ficheros on-line y de forma simultánea. Recibieron al principio el nombre de
 Data Banks, y después, a inicios de los años setenta, el de Data Bases.
La utilización de estos conjuntos de ficheros por parte de los programas de aplicación
 era  excesivamente compleja. De modo que fue Saliendo al mercado software más sofisticado: los Data Base
 Management Systems, que aquí denominamos Sistemas de Gestión de BD (SGBD).
